version: 2
updates:
# Maintain dependencies for Golang
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
