version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - dupl
    - dupword
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - gosmopolitan
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - recvcheck
    - revive
    - staticcheck
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
