name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of validator are you running?
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Example Code
      description: Please provide a code example that demonstrates the issue
      render: go
    validations:
      required: true 